### ISSUE TITLE
gamelogic:  check visibility of piece(s) after move

### ISSUE THREAD

**Issue by kakotoo** [SE-II-group-do-1/stratego-server#24]
überprüfe visibility der pieces vom feind d.h. welche sind sichtbar
sind erst sichtbar wenn man angreift und verliert bzw. gewinnt...

**Comment by hansgriesser** [comment]
@kakotoo , @klaus-maria , @davidpetermann 

Wir ignorieren aktuell noch die Visibility Eigenschaft in der App oder? Soweit ich sehe, wird `isVisible()` nirgends aufgerufen. 

Ich würde das Issue sonst als übergreifendes Issue sehen und auch die Implementierung auf der App-Seite auch mit angehen. Wir müssen die Visibility ja auch "dynamisch" setzen, da jeder Player ja nur seine eigenen Pieces sehen soll oder?
